### PR TITLE
Bug/user revoke unqualified shift

### LINKED ISSUE #158: Users cant release a shift if they don't have the role for it
An admin can effectively add any user to a shift regardless of their role status. This can be handy for adding people to a shift without needing to force the user to take on the role they normally wouldn't; however, a user can't revoke this shift once assigned.

### PR DESCRIPTION
**Pull request by demogorgonzola**
Fixes #158 

Removed the guards from that prevented users from revoking shifts if they didn't have the role for it.

### CODE REVIEW

File: laravel/app/Http/Controllers/SlotController.php [hunk 1]
```diff
@@ -196,7 +189,7 @@ public function adminAssign(Request $request, Slot $slot)
         {
             $username = Helpers::displayName($user);
 
-            $slot->user_id=$user->data->user_id;
+            $slot->user_id=$user->id;
```
Comment (itsrachelfish) [inline laravel/app/Http/Controllers/SlotController.php]: Good catch!
